
try:
	#a=10
	print(a)
	
except:
	print("some error")
finally:
    print("error again")